# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: Release
  ASPNETCORE_ENVIRONMENT: Production

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: Use latest Node

  - script: npm ci
    displayName: npm ci

  - script: npm run webpack
    displayName: npm run webpack

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'
    displayName: dotnet test

  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      projects: 'src/Gaver.Web/Gaver.Web.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
    displayName: dotnet publish

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Gaver'
    displayName: Publish build artifact

  - script: echo "##vso[build.addbuildtag]publish"
    condition: and(succeeded(), contains(variables['Build.SourceVersionMessage'], '#publish'))
    displayName: Add build tag if \#publish
